# Generated by hand for TanPit drain ledger

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrainEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("pit_code", models.CharField(max_length=40)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("operator", models.CharField(blank=True, max_length=64)),
                ("drained_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drain_events",
                        to="pits.pit",
                    ),
                ),
            ],
            options={
                "ordering": ["-drained_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="drainevent",
            index=models.Index(fields=["drained_at"], name="pits_draine_drained_idx"),
        ),
    ]
